//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilityAssist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int building_id { get; set; }
        public int address_id { get; set; }
        public string building_name { get; set; }
        public string building_desc { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
