//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilityAssist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responce
    {
        public int res_id { get; set; }
        public int req_id { get; set; }
        public int user_id { get; set; }
        public string res_comm { get; set; }
        public System.DateTime res_date { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual User User { get; set; }
    }
}
